### ISSUE TITLE
Investigate pattern which can visually split list without semantically splitting them

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-brochure-theme#9]
We should not have to create two separate lists to show ticked lists in two columns,example:

<img width="757" alt="screenshot 2017-01-12 16 37 58" src="https://cloud.githubusercontent.com/assets/505570/21898679/835a8a32-d8e5-11e6-9ea7-50fa7575fb0f.png">

![lists](https://cloud.githubusercontent.com/assets/505570/21898614/4abf01e4-d8e5-11e6-90ad-c79fd27082bb.jpg)

**Comment by anthonydillon** [comment]
First thought is 
```html
<ul class="row">
  <li class="col-6">...</li>
  <li class="col-6">...</li>
  <li class="col-6">...</li>
  <li class="col-6">...</li>
</ul>
```

But with the current implementation of the grid this is not possible. I do not think it would be wise to create list modifiers for its layout as it will be restrictive. For example two, three or four columns.
